name: Publish Release

on:
  workflow_dispatch:
  push:
    tags:
      - v**

jobs:
  pypi:
    runs-on: ubuntu-latest

    permissions:
      contents: write # create the release entry and push the version bump back to main

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set version
        run: uv version ${GITHUB_REF_NAME#v}

      - name: Build
        run: uv build

      - name: Check wheel contents
        run: |
          for file in air_link/air-link.service air_link/.syncignore; do
            unzip -l dist/*.whl | grep -q "$file" || { echo "The wheel is missing $file"; exit 1; }
          done

      - name: Publish PyPI package
        run: uv publish --token ${{ secrets.LIVESYNC_PYPI_API_TOKEN }}

      - name: Create GitHub release entry
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          prerelease: false
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml uv.lock
          git commit -m "Update version to ${GITHUB_REF_NAME#v}"
          git push origin HEAD:main
